### PR TITLE
Apply french réforme territoriale to RegionFR and DepartementFR

### PR DESCRIPTION
**Pull request by bchartier**

### CODE REVIEW

**Comment by bchartier** [comment]
I forgot to mention one modification : replacement of "<dc:rights>Free to all for non commercial use.</dc:rights>" by "<dc:rights>GPL v2</dc:rights>" in order to be coherent with geonetwork license.

Not sure if everybody is ok to apply this modification.

**Comment by fxprunayre** [comment]
Looks good, but I would keep old files at least for Regions as there is number of metadata records which are attached to old regions. So user can choose which regions files to use.

There is odd attribute like https://github.com/neogeo-technologies/geonetwork-util-repository/blob/9b07677b46256d3ca3091cc8d0acbf37b1f0da80/RegionFR.rdf#L291

**Comment by bchartier** [comment]
I've just removed this odd attribute in the Neogeo repo.

**Comment by bchartier** [comment]
> Looks good, but I would keep old files at least for Regions as there is number of metadata records which are attached to old regions. So user can choose which regions files to use.

@fxprunayre: What do you expect from me? Shall I rename the new RegionFR.rdf to RegionFR_2017.rdf in order to have 2 versions of the files? Same thing for departements?

**Comment by fxprunayre** [comment]
> Shall I rename the new RegionFR.rdf to RegionFR_2017.rdf in order to have 2 versions of the files? Same thing for departements?

Yes if we want to be able to use both thesaurus based on user needs.

**Comment by bchartier** [comment]
I close this pull request. I will create a new pull request with the new files.

**Comment by bchartier** [comment]
The new pull request : https://github.com/geonetwork/util-repository/pull/3

**Pull request closed without merging**
